spring:
  profiles:
    active: dev
---
server:
  port: 8091
  
spring:
  profiles: dev
  application:
    name: emp-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8092/eureka/    
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${spring.application.instance_id:${server.port}}
    prefer-ip-address: true
#开启Feign对Hystrix的支持
feign:
  hystrix:
    enabled: true   
#info页面展现配置      
info:
  app:
   name: emp-consumer-8091
  company:
   name: www.sxt.cn
  build:
   artifactId: $project.artifactId$
   version: project.version$    
---
server:
  port: 8091
  
spring:
  profiles: test
  application:
    name: emp-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8092/eureka/    
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${spring.application.instance_id:${server.port}}
    prefer-ip-address: true
#开启Feign对Hystrix的支持
feign:
  hystrix:
    enabled: true   
#info页面展现配置      
info:
  app:
   name: emp-consumer-8091
  company:
   name: www.sxt.cn
  build:
   artifactId: $project.artifactId$
   version: project.version$          